// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	adapter2 "github.com/Wenrh2004/lark-lite-server/internal/file/adapter"
	"github.com/Wenrh2004/lark-lite-server/internal/file/application"
	domain2 "github.com/Wenrh2004/lark-lite-server/internal/file/domain"
	"github.com/Wenrh2004/lark-lite-server/internal/file/infrastructure/producer"
	repository2 "github.com/Wenrh2004/lark-lite-server/internal/file/infrastructure/repository"
	"github.com/Wenrh2004/lark-lite-server/internal/file/infrastructure/third/oss"
	"github.com/Wenrh2004/lark-lite-server/pkg/adapter"
	"github.com/Wenrh2004/lark-lite-server/pkg/application/app"
	"github.com/Wenrh2004/lark-lite-server/pkg/application/register/rpc"
	"github.com/Wenrh2004/lark-lite-server/pkg/application/server/job"
	rpc2 "github.com/Wenrh2004/lark-lite-server/pkg/application/server/rpc"
	"github.com/Wenrh2004/lark-lite-server/pkg/domain"
	"github.com/Wenrh2004/lark-lite-server/pkg/infrastruct/repository"
	"github.com/Wenrh2004/lark-lite-server/pkg/jwt"
	"github.com/Wenrh2004/lark-lite-server/pkg/log"
	"github.com/Wenrh2004/lark-lite-server/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	registry := rpc.NewRegister(viperViper)
	service := adapter.NewService(logger)
	sidSid := sid.NewSid()
	jwtJWT := jwt.NewJwt(viperViper)
	db := repository.NewDB(viperViper, logger)
	client := repository.NewRedis(viperViper)
	ossService := oss.NewService(viperViper)
	repositoryRepository := repository2.NewRepository(logger, db, client, ossService)
	transaction := repository2.NewTransaction(repositoryRepository)
	domainService := domain.NewService(logger, sidSid, jwtJWT, transaction)
	fileRepository := repository2.NewFileRepository(client, ossService)
	fileService := domain2.NewFileService(domainService, fileRepository)
	adapterFileService := adapter2.NewFileService(service, fileService)
	server := application.NewRPCApplication(logger, registry, adapterFileService)
	fileJob := adapter2.NewFileJob(service, fileService)
	jobServer := application.NewJobApplication(viperViper, logger, fileJob)
	appApp := newApp(server, viperViper, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var infrastructureSet = wire.NewSet(repository.NewDB, repository.NewRedis, repository2.NewTransaction, repository2.NewRepository, repository2.NewFileRepository, producer.NewProducer, oss.NewService)

var domainSet = wire.NewSet(domain.NewService, domain2.NewFileService)

var adapterSet = wire.NewSet(adapter.NewService, adapter2.NewFileService, adapter2.NewFileJob)

var applicationSet = wire.NewSet(rpc.NewRegister, application.NewRPCApplication, application.NewJobApplication)

// build App
func newApp(

	rpcServer *rpc2.Server,
	conf *viper.Viper,
	jobServer *job.Server,

) *app.App {
	return app.NewApp(app.WithServer(rpcServer), app.WithServer(jobServer), app.WithName(conf.GetString("app.name")))
}
