// Code generated by Kitex v0.13.1. DO NOT EDIT.

package fileservice

import (
	"context"
	file "github.com/Wenrh2004/lark-lite-server/kitex_gen/file"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PrepareUpload(ctx context.Context, Req *file.PrepareUploadReq, callOptions ...callopt.Option) (r *file.PrepareUploadResp, err error)
	CompleteUpload(ctx context.Context, Req *file.CompleteUploadReq, callOptions ...callopt.Option) (r *file.CompleteUploadResp, err error)
	GetFileStatus(ctx context.Context, Req *file.GetFileStatusReq, callOptions ...callopt.Option) (r *file.GetFileStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFileServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFileServiceClient struct {
	*kClient
}

func (p *kFileServiceClient) PrepareUpload(ctx context.Context, Req *file.PrepareUploadReq, callOptions ...callopt.Option) (r *file.PrepareUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PrepareUpload(ctx, Req)
}

func (p *kFileServiceClient) CompleteUpload(ctx context.Context, Req *file.CompleteUploadReq, callOptions ...callopt.Option) (r *file.CompleteUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CompleteUpload(ctx, Req)
}

func (p *kFileServiceClient) GetFileStatus(ctx context.Context, Req *file.GetFileStatusReq, callOptions ...callopt.Option) (r *file.GetFileStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFileStatus(ctx, Req)
}
