// Code generated by Kitex v0.13.1. DO NOT EDIT.
package awarenessservice

import (
	server "github.com/cloudwego/kitex/server"

	"github.com/Wenrh2004/lark-lite-server/common/kitex_gen/collaboration/awareness"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler awareness.AwarenessService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler awareness.AwarenessService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
