// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID            uint64         `gorm:"column:id;type:bigint unsigned;primaryKey" json:"id"`
	Username      string         `gorm:"column:username;type:varchar(64);not null;comment:登录用户名，唯一" json:"username"`         // 登录用户名，唯一
	Password      string         `gorm:"column:password;type:varchar(255);not null;comment:哈希后的密码" json:"password"`          // 哈希后的密码
	Nickname      string         `gorm:"column:nickname;type:varchar(64);not null;comment:昵称，默认同 username" json:"nickname"`  // 昵称，默认同 username
	AvatarURL     *string        `gorm:"column:avatar_url;type:varchar(255);comment:头像地址" json:"avatar_url"`                 // 头像地址
	BackgroundURL *string        `gorm:"column:background_url;type:varchar(255);comment:背景图地址" json:"background_url"`        // 背景图地址
	Signature     *string        `gorm:"column:signature;type:varchar(255);comment:个性签名" json:"signature"`                   // 个性签名
	Email         *string        `gorm:"column:email;type:varchar(128);comment:邮箱，可用于找回密码" json:"email"`                     // 邮箱，可用于找回密码
	Phone         *string        `gorm:"column:phone;type:varchar(32);comment:手机号" json:"phone"`                             // 手机号
	Gender        byte           `gorm:"column:gender;type:tinyint unsigned;not null;comment:性别：0 未知，1 男，2 女" json:"gender"` // 性别：0 未知，1 男，2 女
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
