// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFileUser = "file_users"

// FileUser 文件与用户的关联表
type FileUser struct {
	ID        uint       `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键，自增ID" json:"id"`            // 主键，自增ID
	FileID    uint64     `gorm:"column:file_id;type:bigint;not null;comment:文件ID，逻辑关联" json:"file_id"`                     // 文件ID，逻辑关联
	UserID    uint64     `gorm:"column:user_id;type:bigint;not null;comment:用户ID，逻辑关联，Sharding Key" json:"user_id"`        // 用户ID，逻辑关联，Sharding Key
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName FileUser's table name
func (*FileUser) TableName() string {
	return TableNameFileUser
}
