// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFile = "files"

// File 文件信息表，存储上传的文件信息
type File struct {
	ID        uint64         `gorm:"column:id;type:bigint;primaryKey;comment:主键，雪花ID" json:"id"`                               // 主键，雪花ID
	Domain    string         `gorm:"column:domain;type:varchar(64);not null;comment:文件业务域" json:"domain"`                      // 文件业务域
	FileName  string         `gorm:"column:file_name;type:varchar(255);not null;comment:文件名" json:"file_name"`                 // 文件名
	FilePath  string         `gorm:"column:file_path;type:varchar(255);not null;comment:文件存储路径" json:"file_path"`              // 文件存储路径
	FileSize  uint64         `gorm:"column:file_size;type:bigint;not null;comment:文件大小（字节）" json:"file_size"`                  // 文件大小（字节）
	FileType  string         `gorm:"column:file_type;type:varchar(32);not null;comment:文件类型" json:"file_type"`                 // 文件类型
	FileHash  string         `gorm:"column:file_hash;type:varchar(64);not null;comment:文件哈希值，Sharding Key" json:"file_hash"`   // 文件哈希值，Sharding Key
	Status    byte           `gorm:"column:status;type:tinyint;not null;comment:状态 0-待上传 1-上传中 2-上传完成 3-上传失败" json:"status"`   // 状态 0-待上传 1-上传中 2-上传完成 3-上传失败
	ExtJSON   *[]byte        `gorm:"column:ext_json;type:json;comment:扩展信息，JSON格式" json:"ext_json"`                            // 扩展信息，JSON格式
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
