basePath: /api/v1
definitions:
  github_com_Wenrh2004_lark-lite-server_common_api_v1.ErrorResponse:
    description: API错误响应格式
    properties:
      code:
        example: 400
        type: integer
      message:
        example: 请求参数错误
        type: string
    type: object
  github_com_Wenrh2004_lark-lite-server_common_api_v1.RefreshResponse:
    description: 刷新访问令牌响应
    properties:
      data:
        $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.UserCertificateResponseBody'
      resp:
        $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.Response'
    type: object
  github_com_Wenrh2004_lark-lite-server_common_api_v1.Response:
    description: API通用响应格式
    properties:
      code:
        example: 0
        type: integer
      data: {}
      message:
        example: success
        type: string
    type: object
  github_com_Wenrh2004_lark-lite-server_common_api_v1.UserAuthRequest:
    description: 用户登录/注册请求参数
    properties:
      password:
        example: password123
        type: string
      username:
        example: testuser
        type: string
    required:
    - password
    - username
    type: object
  github_com_Wenrh2004_lark-lite-server_common_api_v1.UserAuthResponse:
    description: 用户登录/注册响应
    properties:
      data:
        $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.UserAuthResponseBody'
      resp:
        $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.Response'
    type: object
  github_com_Wenrh2004_lark-lite-server_common_api_v1.UserAuthResponseBody:
    description: 用户认证成功返回的用户信息
    properties:
      avatar_url:
        example: https://example.com/avatar.jpg
        type: string
      certificate:
        $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.UserCertificateResponseBody'
      nickname:
        example: 测试用户
        type: string
      user_id:
        example: "123456789"
        type: string
      username:
        example: testuser
        type: string
    type: object
  github_com_Wenrh2004_lark-lite-server_common_api_v1.UserCertificateResponseBody:
    description: 用户访问凭证信息
    properties:
      certificate:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      expires_in:
        example: 3600
        type: integer
    type: object
host: localhost:8888
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Lark Lite User Server API
  version: 1.0.0
paths:
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 用户账户登录认证
      parameters:
      - description: 用户登录请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.UserAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.UserAuthResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.ErrorResponse'
        "401":
          description: 认证失败
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.ErrorResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.ErrorResponse'
      summary: 用户登录
      tags:
      - 用户认证
  /api/v1/user/refresh:
    post:
      consumes:
      - application/json
      description: 使用刷新令牌获取新的访问令牌
      parameters:
      - description: 刷新令牌
        in: header
        name: UserRefreshToken
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 刷新成功
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.RefreshResponse'
        "401":
          description: 认证失败或令牌过期
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.ErrorResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.ErrorResponse'
      summary: 刷新访问令牌
      tags:
      - 用户认证
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 创建新用户账户
      parameters:
      - description: 用户注册请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.UserAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.UserAuthResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.ErrorResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/github_com_Wenrh2004_lark-lite-server_common_api_v1.ErrorResponse'
      summary: 用户注册
      tags:
      - 用户认证
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
